name: svarog_heart_tracker
description: "A new Flutter project."
publish_to: 'none' 

version: 2.1.35+33

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter # Flutter 3.19.3
    
  flutter_localizations:
    sdk: flutter  

  # Нейронка
  tflite_flutter: ^0.10.4

  # Отрисовка графиков
  fl_chart: ^0.61.0

  # Для геренации id
  uuid: ^3.0.7

  # Поиск путя для бд
  path_provider: ^2.1.3

  # Хранение данных
  sqflite: ^2.3.3
  hive: ^2.2.3
  hive_generator: ^2.0.1

  # Виджет динамического текста (подумать как избавиться)
  auto_size_text: ^3.0.0

  # Переход в браузер по ссылкам
  url_launcher: ^6.2.6

  # Маска для текстового поля
  mask_text_input_formatter: ^2.9.0

  # Краш анатлитика
  sentry_flutter: ^7.19.0

  # Работа с блютузом
  flutter_blue_plus: ^1.32.2

  # Navigator 2.0
  auto_route: ^7.9.2

  # dio - отвечает за работу с get, post,delete и тд запросами
  dio: ^5.3.3

  # flutter_svg - отображение векторной графики(.svg файлы)
  flutter_svg: ^2.0.7

  # Предоставляет подробную информацию о устройстве/эмуляторе
  device_info: ^2.0.3

  # package_info - получение информации о приложении: версия,имя и тд
  package_info: ^2.0.2

  # bloc
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # Локальные уведомления
  flutter_local_notifications: ^17.1.2

  # Иньекция Singleton зависимостей
  get_it: ^7.6.4

  # shared_preferences - сохранение небольших данных в локальную память устройства
  shared_preferences: ^2.2.2

  # dartz - используется для работы с состояниями: если приходит ошибка, кладем ее в left(error),инача right(responseModel)
  dartz: ^0.10.1

  # freezed пакет для генерации и следит за мутирвонием данных:
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1

  # для генерации .g файлов, чтобы использовать fromJson и toJson генерацию
  json_serializable: ^6.7.1

  # collection - для работы с коллекциями
  collection: ^1.17.1

  # оверрайдид "==" и "hashCode", чтобы можно было сравнивать классы
  equatable: ^2.0.5

  # используется для настройки локализации
  intl_utils: ^2.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Navigator 2.0
  auto_route_generator: ^7.3.2

  # build_runner - генерация freezed файлов
  build_runner: ^2.3.3

  #  flutter_gen_runner - используется для генерации классов ассетов
  flutter_gen_runner: ^5.3.0

  # TODO стоит добавить эти метрики, чтобы убрать не используемые файлы
  # dart_code_metrics: ^5.7.2

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/model.tflite


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 800
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400

flutter_gen:
  output: lib/core/common/
  line_length: 120
  integrations:
    flutter_svg: true

# настройка локализации
flutter_intl:
  enabled: true
  main_locale: ru
  arb_dir: lib/core/l10n/arb
  output_dir: lib/core/l10n/generated