/// Flutter icons BaseIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BaseIcons
///      fonts:
///       - asset: fonts/BaseIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BaseIcons {
  BaseIcons._();

  static const _kFontFam = 'BaseIcons';
  static const String? _kFontPkg = null;

  static const IconData history = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hide = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exit = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning_shield = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_full = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
